
	ORG 0000h 	;ENDEREÇO QUE APONTA A INTERRUPÇÃO RESET (EXTERNA - PINO 9))
	JMP INICIO
;------------------------------------------------------------------------------------------------

INICIO:	MOV P2, #000h
	CALL CONTA
	SETB P2.0
	CALL CONTA
	CLR P2.0
	SETB P2.1
	CALL CONTA
	CLR P2.1
	SETB P2.2
	CALL CONTA
	CLR P2.2
	SETB P2.3
	CALL CONTA
	CLR P2.3
	SETB P2.4
	CALL CONTA
	CLR P2.4
	SETB P2.5
	CALL CONTA
	CLR P2.5
	SETB P2.6
	CALL CONTA
	CLR P2.6
	SETB P2.7
	CALL CONTA
	CLR P2.7
	CALL CONTA
	SETB P2.7
	CALL CONTA
	CLR P2.7
	SETB P2.6
	CALL CONTA
	CLR P2.6
	SETB P2.5
	CALL CONTA
	CLR P2.5
	SETB P2.4
	CALL CONTA
	CLR P2.4
	SETB P2.3
	CALL CONTA
	CLR P2.3
	SETB P2.2
	CALL CONTA
	CLR P2.2
	SETB P2.1
	CALL CONTA
	CLR P2.1
	SETB P2.0
	CALL CONTA
	JMP INICIO

CONTA:	SETB TR0	;INICIA O TIMER_0
LOOP:	JNB TF0, LOOP	;ENQUANTO TF0 NÃO FOR 1, EXECUTARÁ O LOOP. QUANDO VIRAR 1, IRÁ PARA AS LINHAS ABAIXO
	INC R1
	CLR TR0		;DESLIGA O TIMER, FAZ ELE PARAR DE CONTAR
	CLR TF0		;PARA DESABILITAR O FLAG
	CJNE R1, #040d, CONTA	;COMPARA R1 COM #10h ENQUANTO FOR DIFERENTE SE MANTEM NO LOOP
	MOV R1,#00h
	RET		;FAZ VOLTAR NA LINHA ABAIXO DA ONDE FOI DADO O "CALL"

	END
