ORG 0000h
	MOV P2 , #0FFh
	CLR P2.7

INICIO:	MOV P2 , #0FFh
	CLR P2.7
	CLR P2.0		;ASCENDE O LED VERMELHO NORTE
	CALL CONTA2
	SETB P2.0
	CLR P2.1		;ASCENE O LED VERDE
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	SETB P2.1
	CLR P2.2
	CALL CONTA2
	SETB P2.2
	CLR P2.1
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	CALL CONTA2
	SETB P2.1
	JMP INICIO
	
	CONTA2:	SETB TR0	;INICIA O TIMER_0
LOOP2:	JNB TF0, LOOP2	;ENQUANTO TF0 NÃO FOR 1, EXECUTARÁ O LOOP. QUANDO VIRAR 1, IRÁ PARA AS LINHAS ABAIXO
	INC R0
	CLR TR0		;DESLIGA O TIMER, FAZ ELE PARAR DE CONTAR
	CLR TF0		;PARA DESABILITAR O FLAG
	CJNE R0, #246d, CONTA2
	MOV R0, #00h
	RET		;FAZ VOLTAR NA LINHA ABAIXO DA ONDE FOI DADO O "CALL"
	
	JMP INICIO