			;MIC
	;MARCONE AUGUSTO 
	;P1.7 LED VERDE DOS CARROS
	;P1.6 LED AMARELO DOS CARROS
	;P1.5 LED VERMELHO DOS CARROS
	;P2.0 LED VERDE PEDESTRE
	;P2.1 LED VERMELHO PEDESTRE

	ORG 0000h 	;ENDEREÇO QUE APONTA A INTERRUPÇÃO RESET (EXTERNA - PINO 9))
	JMP CONFIG
;------------------------------------------------------------------------------------------------

	ORG 00003h 	;ENDEREÇO QUE APOTA A INTERRUPÇÃO INT_0 ( EXTERNA - PINO P3.2)
	;INSTRUÇÕES
	CALL INTERRUP
	NOP	
	RETI 
;------------------------------------------------------------------------------------------------

CONFIG: MOV R1, #00h	;FORÇANDO R1 A SER 0 (PARA GARANTIA)
	MOV R0, #00h	;FORÇANDO R0 A SER 0 (PARA GARANTIA)
	MOV P1, #00h	;FORÇANDO R1 A SER 0 (PARA GARANTIA)
	MOV P2, #00h	;FORÇANDO R0 A SER 0 (PARA GARANTIA)
	SETB PX0
	MOV IE , #10000001b

INICIO:	
	
	SETB P1.7	;ASCENDE LED VERDE CARROS
	SETB P2.1	;ASCENDE O VERMELHO DO PEDESTRE
	JMP INICIO

INTERRUP: 
	CALL CONTA
	CALL CONTA
	CLR P2.1	;APAGA O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	SETB P2.1	;ASCENDE O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	CLR P2.1	;APAGA O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	SETB P2.1	;ASCENDE O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	CLR P2.1	;APAGA O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	SETB P2.1	;ASCENDE O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	CLR P2.1	;APAGA O LED VERMELHO DO PEDESTRE
	SETB P1.6	;ASCENDE O LED AMARELO DOS CARROS
	CLR P1.7	;APAGA O VERDE DOS CARROS
	CALL CONTA2
	SETB P2.1	;ASCENDE O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	CLR P2.1	;APAGA O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	SETB P2.1	;ASCENDE O LED VERMELHO DO PEDESTRE
	CALL CONTA2
	CLR P1.6	;APAGA LED AMARELO DOS CARROS
	CLR P2.1	;APAGA O LED VERMELHO DO PEDESTRE
	SETB P1.5	;ASCENDE O LED VERMELHO DOS CARROS
	SETB P2.0	;ASCENDE O LED VERDE DO PEDESTRE
	CALL CONTA	;QUANDO CHAMAR O "CALL" USAR NO FINAL "RET" INVÉS DE "JMP $"
	CALL CONTA
	CALL CONTA
	CALL CONTA
	CLR P2.0	;APAGA O LED VERDE DO PEDESTRE
	CALL CONTA2
	SETB P2.0	;ASCENDE O LED VERDE DO PEDESTRE
	CALL CONTA2
	CLR P2.0	;APAGA O LED VERDE DO PEDESTRE
	CALL CONTA2
	SETB P2.0	;ASCENDE O LED VERDE DO PEDESTRE
	CALL CONTA2
	CLR P2.0	;APAGA O LED VERDE DO PEDESTRE
	CALL CONTA2
	SETB P2.0	;ASCENDE O LED VERDE DO PEDESTRE
	CALL CONTA2
	CLR P2.0	;APAGA O LED VERDE DO PEDESTRE
	CALL CONTA2
	SETB P2.0	;ASCENDE O LED VERDE DO PEDESTRE
	CALL CONTA2
	CLR P2.0	;APAGA O LED VERDE DO PEDESTRE
	CALL CONTA2
	SETB P2.0	;ASCENDE O LED VERDE DO PEDESTRE
	CALL CONTA2
	CLR P2.0	;APAGA O LED VERDE DO PEDESTRE	
	CLR P1.5
	RET

CONTA:	SETB TR0	;INICIA O TIMER_0
LOOP:	JNB TF0, LOOP	;ENQUANTO TF0 NÃO FOR 1, EXECUTARÁ O LOOP. QUANDO VIRAR 1, IRÁ PARA AS LINHAS ABAIXO
	INC R1
	CLR TR0		;DESLIGA O TIMER, FAZ ELE PARAR DE CONTAR
	CLR TF0		;PARA DESABILITAR O FLAG
	CJNE R1, #0FFh, CONTA	;COMPARA R1 COM #10h ENQUANTO FOR DIFERENTE SE MANTEM NO LOOP
	MOV R1,#00h
	RET		;FAZ VOLTAR NA LINHA ABAIXO DA ONDE FOI DADO O "CALL"

	
CONTA2:	SETB TR0	;INICIA O TIMER_0
LOOP2:	JNB TF0, LOOP2	;ENQUANTO TF0 NÃO FOR 1, EXECUTARÁ O LOOP. QUANDO VIRAR 1, IRÁ PARA AS LINHAS ABAIXO
	INC R0
	CLR TR0		;DESLIGA O TIMER, FAZ ELE PARAR DE CONTAR
	CLR TF0		;PARA DESABILITAR O FLAG
	CJNE R0, #123d, CONTA2
	MOV R0, #00h
	RET		;FAZ VOLTAR NA LINHA ABAIXO DA ONDE FOI DADO O "CALL"
	

	END
